# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xorgate.xdc

# Block Designs: bd/xorgate/xorgate.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xorgate || ORIG_REF_NAME==xorgate} -quiet] -quiet

# IP: bd/xorgate/ip/xorgate_xup_nand2_0_2/xorgate_xup_nand2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xorgate_xup_nand2_0_2 || ORIG_REF_NAME==xorgate_xup_nand2_0_2} -quiet] -quiet

# IP: bd/xorgate/ip/xorgate_xup_nand2_0_3/xorgate_xup_nand2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xorgate_xup_nand2_0_3 || ORIG_REF_NAME==xorgate_xup_nand2_0_3} -quiet] -quiet

# IP: bd/xorgate/ip/xorgate_xup_nand2_0_0/xorgate_xup_nand2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xorgate_xup_nand2_0_0 || ORIG_REF_NAME==xorgate_xup_nand2_0_0} -quiet] -quiet

# IP: bd/xorgate/ip/xorgate_xup_nand2_0_1/xorgate_xup_nand2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xorgate_xup_nand2_0_1 || ORIG_REF_NAME==xorgate_xup_nand2_0_1} -quiet] -quiet

# XDC: bd/xorgate/xorgate_ooc.xdc
