set_property SRC_FILE_INFO {cfile:C:/Users/toure.o/Desktop/Lab0/project_1/project_1.srcs/constrs_1/new/xorgate.xdc rfile:../../../project_1.srcs/constrs_1/new/xorgate.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports a]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports b]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports c]
